name: Keep Server Online

on:
  schedule:
    - cron: "*/15 * * * *" 

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to /keep_online
        run: curl -X GET --silent --output /dev/null ${{ secrets.SERVER_URL }}
